### PR TITLE
Adds ability to compare the current and incoming changes

### LINKED ISSUE #21: Consistent action button placement
A very nice extension.

I have a small quirk from a UX perspective. I think it would be nice to have a consistent order for the accept* buttons. I see that they keep shuffling between conflicts. I'm using version 0.6.1 with latest vscode (v1.11.2)
image

### PR DESCRIPTION
**Pull request by eamodio**
This is something I've been wanting for a while now and I feel like it fits in well with the spirit of better-merge (hopefully you do too!).

This PR fixes #21 and adds a `Compare changes` code lens at the end. Clicking on the code lens, opens a diff of the current vs incoming changes for that conflict.

Let me know what you think.

### CODE REVIEW

**Comment by pprice** [comment]
Hey @eamodio thanks for putting this together! I like the feature idea, and thanks for fixing #21 in the process. 

I found a couple of issues from testing: 

 - CodeLens for "Compare changes" attempts to execute `better-merge.diff`, but the command is registered as `better-merge.compare` in `commandHandler.ts` 
 - `better-merge.diff` or `better-merge.compare` is missing from the package.json - we might not need this, but it would be nice to launch from the command palette against the current selection (small change, we can use `commandHandler.ts!findConflictContainingSelection`).
 - After fixing these up in a local branch, compare changes fails with "Unable to show comparison", this was due to `uri.with({ scheme: 'file', query: undefined })`, passing undefined to query, doesn't appear to clear the query field, however `uri.with({ scheme: 'file', query: '' })` will correctly clear the query for the uri. This *might* be windows specific? 

I'm going to go ahead and merge your changes, and submit a PR with the fixes and tag you in it. 

Thanks again!

**Comment by eamodio** [comment]
Doh -- sorry, I had it as `better-merge.diff` at first, and renamed it at the end and apparently missed a case (my excuse is it was late ;) -- as lame as that is)

Adding them to the `project.json` sounds great -- I didn't want to go too far with this in case you weren't interested ;)

Hrm -- honestly I was worried that query might not like `undefined` but when I tried it all seemed fine. And I am on Windows too. Odd, but `''` makes perfect sense.

Awesome -- thank you!

**Comment by eamodio** [comment]
@pprice I didn't go down this path (and I'm not really sure it is worth it), but was toying with the idea of another compare, that actually generates the 2 sides (current vs incoming) -- so the left would be as if you accepted all current, and the right would be as if you accepted all incoming -- but I'm not sure that is much more valuable then this version or not (and its a bit more work)

Any thoughts?

**Comment by pprice** [comment]
@eamodio I think all these variants are cool, and willing to have them - the issue I see if giving a balanced UX, that a) lets the user know the capability is there but b) no overwhelming them (e.g. adding more code lens items). 

Ideally I'd like something like a top level `Compare...` code lens item, acting as a "top level menu" into different modes, but vscode is pretty restrictive on UI elements (and rightly so). 

My gut feeling would be to start with basic commands and promote up to code lens if users ask / new UI affordances make it into vscode.

**Comment by eamodio** [comment]
Sounds good -- I'm not convinced that mode really provides much over what is there now anyway -- but figured I'd throw it out there ;)

**Comment by deepu105** [comment]
Awesome. This is much better than the atom plugin

**Pull request merged**
